### ISSUE TITLE
Path to csv file is fixed

### ISSUE THREAD

**Issue by LukeNeedle** [HungryHedgie/Processing-Damped-spring-SHM-data#2]
Currently the path to the csv file that the program tries to use is set to `C:\\Users\\jedsk\\Documents\\_My Documents\\Work\\A Level\\Physics\\dampedSpringSHMPractical.csv`. A potential solution is that the user could enter a path to the csv file when the program is opened or use a relative path and store the csv file with the compiled program.

**Comment by JedSkilling** [comment]
Entering an absolute path (not a relative one) is now implemented along with a bit clearer explanation of what to do.

Relative path not implemented as usually this is ran from the debug folder and that can be annoying to find/easy to forget and might not be intuitive to use. (If I add a release .exe then maybe I'll implement this)
